version: "3"
services:
  mtbimporter:
    restart: unless-stopped
    image: ghcr.io/buschlab/mtbimporter:latest
    command: "/app/settings.yaml"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./settings.yaml:/app/settings.yaml"
      - "./input:/app/input"
      - "./mapper:/app/mapper"
      - "./processed:/app/processed"
      - "../../study:/app/study"
      - "./template:/app/template"
      - "../../reports:/app/reports"
    networks:
      - miracum-cbioportal_cbioportal_net

networks:
  miracum-cbioportal_cbioportal_net:
    external: true